name: candian_cart
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1


environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  icons_plus: ^5.0.0
  lottie: ^2.7.0
  image_picker: ^1.0.8
  otp_text_field: ^1.1.3
  flutter_svg: ^2.0.10+1
  carousel_slider: ^5.0.0
  table_calendar: ^3.1.2
  google_fonts: ^6.2.1
  flutter_datetime_picker: ^1.5.1
  provider: ^6.1.2
  intl: ^0.19.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.3.2
  google_sign_in: ^6.2.1
  pin_code_text_field: ^1.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

    
  fonts:
    - family: main
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat-Black.ttf

  
